# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#   pull_request:
#     branches: [ main ]
  workflow_dispatch:
  schedule:
    #   分 时 日 月 周
    - cron: "* */1200 * * *" # 一天更新一次

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: sync UpdateTestApp
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/UpdateTestApp.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd UpdateTestApp
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi

      - name: sync check_sdk_scheduled
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/check_sdk_scheduled.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd check_sdk_scheduled
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi


      - name: sync ActionsReport
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/ActionsReport.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd ActionsReport
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi

      - name: sync ReportWeather
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/ReportWeather.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd ReportWeather
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi



      - name: sync s2
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/s2.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd s2
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi


      - name: sync UpdateGithubIcp
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/UpdateGithubIcp.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd UpdateGithubIcp
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi

      - name: sync someInfoGoGo
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/TestJken66/someInfoGoGo.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd UpdateGithubIcp
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi

      # Runs a set of commands using the runners shell
      - name: sync parser_proxy_1
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/parserpp/parser_proxy_1.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd parser_proxy_1
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi

      # Runs a set of commands using the runners shell
      - name: sync Every15m_runner-get_proxy_2
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/parserpp/Every15m_runner-get_proxy_2.git
          if [ $# == 0 ]; then
            echo  "克隆成功......"
            cd Every15m_runner-get_proxy_2
            chmod -R 777 *
            git config core.filemode false
            echo -e "* $(date "+%Y%m%d-%H%M%S")">>time.md

            git config --global user.name "GithubAction"
            git config --global user.email "sanbo.xyz@gmail.com"
            if [ -z "$(git status --porcelain)" ]
            then
              echo "============================nothing to update.==============================="
            else
              git add .
              git commit -am "GitHubAction: triggle by commit ${{ github.sha }}. created by ${{ github.workflow }}." -a
              git push
            fi
          fi
